In [3]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Eksempel!234@localhost:3306/brondby")

print("Forbindelse oprettet ✅")

Forbindelse oprettet ✅

In [4]:
df_matches = pd.read_sql("SELECT * FROM matches;", engine)
df_tickets = pd.read_sql("SELECT * FROM tickets;", engine)
df_fb      = pd.read_sql("SELECT * FROM fb_order_lines;", engine)
df_profiles= pd.read_sql("SELECT * FROM profiles;", engine)

print("Matches:", df_matches.shape)
print("Tickets:", df_tickets.shape)
print("FB Orders:", df_fb.shape)
print("Profiles:", df_profiles.shape)

Matches: (156, 10)
Tickets: (1656875, 18)
FB Orders: (2186416, 12)
Profiles: (196649, 7)

Blok A

In [118]:
# billetsalg pr. kamp-id
tickets_per_match = (
    df_tickets.groupby("match_id")["ticket_id"]
              .count()
              .reset_index(name="tickets_sold")
)
tickets_per_match.sort_values("tickets_sold", ascending=False).head(10)

    match_id  tickets_sold
99      5537         24185
53      3161         19432
51      3029         18910
94      5240         18361
21      1742         18235
79      4514         18016
76      4316         17961
74      4151         17886
10       917         17694
83      4712         17586

Blok B

In [119]:

# sørg for tidstyper
df_tickets["attendance"] = pd.to_datetime(df_tickets["attendance"], errors="coerce")
df_matches["Kampdato_dt"] = pd.to_datetime(df_matches["Kampdato"], errors="coerce").dt.date

# brug kun billetter der er scannet
att = df_tickets.dropna(subset=["attendance"]).copy()
att["att_date"] = att["attendance"].dt.date

# mest hyppige attendance-dato pr. match_id (mode)
mode_att_date = (
    att.groupby("match_id")["att_date"]
       .agg(lambda s: s.value_counts().idxmax())
       .reset_index(name="att_date")
)
mode_att_date.head()

   match_id    att_date
0       621  2022-07-17
1       622  2022-07-24
2       623  2022-08-14
3       624  2022-08-29
4       653  2022-07-28

Blok C

In [120]:
mapping = mode_att_date.merge(
    df_matches,
    left_on="att_date",
    right_on="Kampdato_dt",
    how="left"
)[["match_id","Kampnavn","Kampdato","Kampstart","Sæson","Turnering","Turneringstype"]]

mapping.head(10)

,match_id,Kampnavn,Kampdato,Kampstart,Sæson,Turnering,Turneringstype
0,621,2022-07-17 | Brøndby IF - AGF,2022-07-17,2022-07-17 18:00:00,2022/23,Superliga,Superliga
1,622,2022-07-24 | Brøndby IF - FC Nordsjælland,2022-07-24,2022-07-24 16:00:00,2022/23,Superliga,Superliga
2,623,2022-08-14 | Brøndby IF - OB,2022-08-14,2022-08-14 18:00:00,2022/23,Superliga,Superliga
3,624,2022-08-29 | Brøndby IF - FC Midtjylland,2022-08-29,2022-08-29 19:00:00,2022/23,Superliga,Superliga
4,653,2022-07-28 | Brøndby IF - Pogoń Szczecin,2022-07-28,2022-07-28 20:00:00,2022/23,UEFA Europa Conference League,UEFA
5,719,2022-08-04 | Brøndby IF - FC Basel,2022-08-04,2022-08-04 20:30:00,2022/23,UEFA Europa Conference League,UEFA
6,752,2022-09-11 | Brøndby IF - Randers FC,2022-09-11,2022-09-11 16:00:00,2022/23,Superliga,Superliga
7,818,2022-10-02 | Brøndby IF - Lyngby BK,2022-10-02,2022-10-02 16:00:00,2022/23,Superliga,Superliga
8,851,2022-10-30 | Brøndby IF - AaB,2022-10-30,2022-10-30 18:00:00,2022/23,Superliga,Superliga
9,884,2022-11-13 | Brøndby IF - Viborg FF,2022-11-13,2022-11-13 16:00:00,2022/23,Superliga,Superliga

Blok D.1

In [121]:
tickets_per_match = (
    df_tickets.groupby("match_id")["ticket_id"]
              .count()
              .reset_index(name="tickets_sold")
)

Blok D.2

In [122]:
tickets_with_names = tickets_per_match.merge(mapping, on="match_id", how="left")
tickets_with_names = tickets_with_names.sort_values("tickets_sold", ascending=False)
tickets_with_names.head(10)   # Top 10 kampe

,match_id,tickets_sold,Kampnavn,Kampdato,Kampstart,Sæson,Turnering,Turneringstype
99,5537,24185,2025-08-28 | Brøndby IF - RC Strasbourg,2025-08-28,2025-08-28 20:00:00,2025/26,UEFA Europa Conference League,UEFA
53,3161,19432,2024-08-08 | Brøndby IF - Legia Warszawa,2024-08-08,2024-08-08 19:00:00,2024/25,UEFA Europa Conference League,UEFA
51,3029,18910,2024-07-25 | Brøndby IF - KF Llapi,2024-07-25,2024-07-25 19:00:00,2024/25,UEFA Europa Conference League,UEFA
94,5240,18361,2025-08-14 | Brøndby IF - Vikingur Reykjavik,2025-08-14,2025-08-14 19:30:00,2025/26,UEFA Europa Conference League,UEFA
21,1742,18235,2023-09-24 | Brøndby IF - FC København,2023-09-24,2023-09-24 14:00:00,2023/24,Superliga,Superliga
79,4514,18016,2025-04-18 | Brøndby IF - FC Nordsjælland,2025-04-18,2025-04-18 19:00:00,2024/25,Superliga,Superliga
76,4316,17961,2025-03-16 | Brøndby IF - Silkeborg IF,2025-03-16,2025-03-16 17:00:00,2024/25,Superliga,Superliga
74,4151,17886,2025-02-14 | Brøndby IF - Viborg FF,2025-02-14,2025-02-14 19:00:00,2024/25,Superliga,Superliga
10,917,17694,2022-10-16 | Brøndby IF - FC København,2022-10-16,2022-10-16 14:00:00,2022/23,Superliga,Superliga
83,4712,17586,2025-05-04 | Brøndby IF - FC København,2025-05-04,2025-05-04 16:00:00,2024/25,Superliga,Superliga

Views

In [123]:
ticket_types = (
    df_tickets.groupby(["match_id","ticket_type"])["ticket_id"]
              .count()
              .reset_index(name="count")
              .pivot(index="match_id", columns="ticket_type", values="count")
              .fillna(0)
              .reset_index()
)

In [124]:
sections = (
    df_tickets.groupby(["match_id","section_display"])["ticket_id"]
              .count()
              .reset_index(name="count")
              .pivot(index="match_id", columns="section_display", values="count")
              .fillna(0)
              .reset_index()
)

In [125]:
# 1. Tickets med kampnavne/datoer
tickets_with_names = df_tickets.merge(
    mapping, on="match_id", how="left"
)

# 2. Gennemsnitlige scans
avg_scans = (
    df_tickets.groupby("match_id")
              .agg(avg_scans=("ticket_id", "count"))
              .reset_index()
)

# 3. Peak scans pr. kamp (hvis du har scan_time-kolonne)
peak_scans = (
    df_tickets.groupby(["match_id", "attendance"])
              .size()
              .reset_index(name="scans")
              .sort_values(["match_id", "scans"], ascending=[True, False])
              .groupby("match_id")
              .head(1)
              .rename(columns={"attendance": "peak_minute", "scans": "peak_scans"})
)

# 4. Ticket typer
ticket_types = (
    df_tickets.groupby(["match_id", "ticket_type"])["ticket_id"]
              .count()
              .reset_index(name="count")
              .pivot(index="match_id", columns="ticket_type", values="count")
              .fillna(0)
              .reset_index()
)

# 5. Sektioner
sections = (
    df_tickets.groupby(["match_id", "section_display"])["ticket_id"]
              .count()
              .reset_index(name="count")
              .pivot(index="match_id", columns="section_display", values="count")
              .fillna(0)
              .reset_index()
)

In [126]:
tickets_full = (tickets_with_names
    .merge(avg_scans, on="match_id", how="left")
    .merge(peak_scans[["match_id","peak_minute","peak_scans"]], on="match_id", how="left")
    .merge(ticket_types, on="match_id", how="left")      # <-- nyt
    .merge(sections, on="match_id", how="left")          # <-- nyt
)

tickets_full.head()

,id,match_id,object_id,email,transaction_id,created_at_source,status,cancelled_at,price_type,entrance_code,...,Vilfort Lounge_Blok 5,Vilfort Lounge_Blok 6,Vilfort Lounge_Hertha BSC Lounge,Vilfort Lounge_Legende Logen,Vilfort Lounge_Tårn 2,Vilfort Lounge_Tårn 3,Vilfort Lounge_Tårn 4,Vilfort Lounge_Tårn 5,Vilfort Lounge_Tårn 6,Zachodnia_225
0,1,4151,6472005.0,c10decfcd58a1781ceeeb73acef382242b5e7a92c2588d...,5787661,2025-01-29 13:33:40,active,NaT,Voksen,C,...,16.0,13.0,0.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,4151,6471022.0,fe68390a5c8a725710665b7ef1de9abfe2438d4b3716ea...,5787339,2025-01-29 13:28:50,active,NaT,Voksen,C_STEMNING,...,16.0,13.0,0.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,4151,6470545.0,d5c7083d7dc08773a9a56a38f8492fc3730f72d7645406...,5786003,2025-01-29 13:27:23,active,NaT,Voksen,C,...,16.0,13.0,0.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,4151,6472662.0,45d41cfba67f62bbe0afddc9438ee3410fd6a6e73acdaf...,5788179,2025-01-29 13:38:53,active,NaT,Fribillet (Voksen),H,...,16.0,13.0,0.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,4151,6471779.0,834ef7fd47e75815caf5fea7797280c6fd203c96fc74a3...,5787682,2025-01-29 13:31:05,active,NaT,Fribillet (Voksen),H,...,16.0,13.0,0.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0

In [127]:
# Sørg for tidstyper
df_tickets["attendance"] = pd.to_datetime(df_tickets["attendance"], errors="coerce")
df_matches["Kampdato_dt"] = pd.to_datetime(df_matches["Kampdato"], errors="coerce").dt.date

# Find mest hyppige attendance-dato pr kamp_id
att = df_tickets.dropna(subset=["attendance"]).copy()
att["att_date"] = att["attendance"].dt.date

mode_att_date = (
    att.groupby("match_id")["att_date"]
    .agg(lambda s: s.value_counts().idxmax())
    .reset_index(name="att_date")
)

# Merge for at få kampinfo + match_id
mapping = mode_att_date.merge(
    df_matches,
    left_on="att_date",
    right_on="Kampdato_dt",
    how="left"
)

In [128]:
# Antal solgte billetter
tickets_per_match = (
    df_tickets.groupby("match_id")["ticket_id"]
    .count()
    .reset_index(name="tickets_sold")
)

# Gennemsnitlige scanninger (hvis attendance = scanninger)
avg_scans = (
    df_tickets.groupby("match_id")
    .agg(avg_scans=("attendance", "count"))
    .reset_index()
)

# Peak scanninger per kamp
peak_scans = (
    df_tickets.groupby(["match_id", "attendance"])
    .size()
    .reset_index(name="scans")
    .sort_values(["match_id", "scans"], ascending=[True, False])
    .groupby("match_id")
    .head(1)
    .rename(columns={"attendance": "peak_minute", "scans": "peak_scans"})
)

# Ticket types
ticket_types = (
    df_tickets.groupby(["match_id","ticket_type"])["ticket_id"]
    .count()
    .reset_index()
    .pivot(index="match_id", columns="ticket_type", values="ticket_id")
    .fillna(0)
    .reset_index()
)

# Sections
sections = (
    df_tickets.groupby(["match_id","section_display"])["ticket_id"]
    .count()
    .reset_index()
    .pivot(index="match_id", columns="section_display", values="ticket_id")
    .fillna(0)
    .reset_index()
)

In [129]:
tickets_summary = (
    mapping
    .merge(tickets_per_match, on="match_id", how="left")
    .merge(avg_scans, on="match_id", how="left")
    .merge(ticket_types, on="match_id", how="left")
    .merge(sections, on="match_id", how="left")
    .merge(peak_scans[["match_id", "peak_minute", "peak_scans"]], on="match_id", how="left")
)

tickets_summary[[
    "match_id", "Kampnavn", "Kampdato", "Kampstart", 
    "Sæson", "Turnering", "Hjemmehold", "Udehold", 
    "tickets_sold", "avg_scans", "peak_scans", "peak_minute"
]].head(10)

,match_id,Kampnavn,Kampdato,Kampstart,Sæson,Turnering,Hjemmehold,Udehold,tickets_sold,avg_scans,peak_scans,peak_minute
0,621,2022-07-17 | Brøndby IF - AGF,2022-07-17,2022-07-17 18:00:00,2022/23,Superliga,Brøndby IF,AGF,11249,16908,14,2022-07-17 17:16:39
1,622,2022-07-24 | Brøndby IF - FC Nordsjælland,2022-07-24,2022-07-24 16:00:00,2022/23,Superliga,Brøndby IF,FC Nordsjælland,11737,16845,12,2022-07-24 15:13:18
2,623,2022-08-14 | Brøndby IF - OB,2022-08-14,2022-08-14 18:00:00,2022/23,Superliga,Brøndby IF,OB,11458,17822,11,2022-08-14 17:40:50
3,624,2022-08-29 | Brøndby IF - FC Midtjylland,2022-08-29,2022-08-29 19:00:00,2022/23,Superliga,Brøndby IF,FC Midtjylland,10662,16544,12,2022-08-29 18:44:52
4,653,2022-07-28 | Brøndby IF - Pogoń Szczecin,2022-07-28,2022-07-28 20:00:00,2022/23,UEFA Europa Conference League,Brøndby IF,Pogoń Szczecin,10451,15211,10,2022-07-28 19:21:39
5,719,2022-08-04 | Brøndby IF - FC Basel,2022-08-04,2022-08-04 20:30:00,2022/23,UEFA Europa Conference League,Brøndby IF,FC Basel,15560,14907,10,2022-08-04 19:53:23
6,752,2022-09-11 | Brøndby IF - Randers FC,2022-09-11,2022-09-11 16:00:00,2022/23,Superliga,Brøndby IF,Randers FC,15076,21661,14,2022-09-11 15:42:52
7,818,2022-10-02 | Brøndby IF - Lyngby BK,2022-10-02,2022-10-02 16:00:00,2022/23,Superliga,Brøndby IF,Lyngby BK,13330,19023,12,2022-10-02 15:39:21
8,851,2022-10-30 | Brøndby IF - AaB,2022-10-30,2022-10-30 18:00:00,2022/23,Superliga,Brøndby IF,AaB,12304,18616,11,2022-10-30 18:23:55
9,884,2022-11-13 | Brøndby IF - Viborg FF,2022-11-13,2022-11-13 16:00:00,2022/23,Superliga,Brøndby IF,Viborg FF,13966,20984,13,2022-11-13 16:33:11

In [130]:
# 1. Klargør datoer
df_fb["date_only"] = pd.to_datetime(df_fb["datetime"]).dt.date
mapping["date_only"] = pd.to_datetime(mapping["Kampdato"]).dt.date

# 2. Join F&B ordrer til mapping
fb_with_matches = df_fb.merge(
    mapping[["match_id", "Kampnavn", "Kampdato", "Kampstart", "date_only"]],
    on="date_only",
    how="left"
)

# 3. Omsætning pr. kamp
revenue_per_match = (
    fb_with_matches.groupby("match_id")["price_paid_in_cents"]
    .sum()
    .reset_index(name="total_revenue_DKK")
)
revenue_per_match["total_revenue_DKK"] = revenue_per_match["total_revenue_DKK"] / 100

# 4. Peak ordrer per kamp
orders_per_minute = (
    fb_with_matches
    .set_index("datetime")
    .groupby("match_id")
    .resample("1T")
    .size()
    .reset_index(name="orders_count")
)

peak_orders = orders_per_minute.loc[
    orders_per_minute.groupby("match_id")["orders_count"].idxmax()
].reset_index(drop=True)

peak_orders.rename(
    columns={"datetime": "fb_peak_time", "orders_count": "fb_peak_orders"},
    inplace=True
)

# 5. Merge ind i tickets_summary
tickets_summary = (
    tickets_summary
    .merge(revenue_per_match, on="match_id", how="left")
    .merge(peak_orders[["match_id", "fb_peak_time", "fb_peak_orders"]], on="match_id", how="left")
)

# 6. Ekstra: vejrlig proxy
tickets_summary["month"] = pd.to_datetime(tickets_summary["Kampdato"]).dt.month
tickets_summary["season_weather"] = tickets_summary["month"].map({
    12: "Vinter", 1: "Vinter", 2: "Vinter",
    3: "Forår", 4: "Forår", 5: "Forår",
    6: "Sommer", 7: "Sommer", 8: "Sommer",
    9: "Efterår", 10: "Efterår", 11: "Efterår"
})

tickets_summary.head(10)

C:\Users\Haashir Khan\AppData\Local\Temp\ipykernel_58636\2793275901.py:25: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  .resample("1T")
C:\Users\Haashir Khan\AppData\Local\Temp\ipykernel_58636\2793275901.py:26: FutureWarning: DataFrameGroupBy.resample operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .size()

,match_id,att_date,Kampdato,Kampnavn,Kampstart,Sæson,Turnering,Turneringstype,Hjemmehold,Hjemmeholdsforkortelse,...,Vilfort Lounge_Tårn 5,Vilfort Lounge_Tårn 6,Zachodnia_225,peak_minute,peak_scans,total_revenue_DKK,fb_peak_time,fb_peak_orders,month,season_weather
0,621,2022-07-17,2022-07-17,2022-07-17 | Brøndby IF - AGF,2022-07-17 18:00:00,2022/23,Superliga,Superliga,Brøndby IF,BIF,...,0.0,0.0,0.0,2022-07-17 17:16:39,14,1485862.04,2022-07-17 18:55:00,254.0,7,Sommer
1,622,2022-07-24,2022-07-24,2022-07-24 | Brøndby IF - FC Nordsjælland,2022-07-24 16:00:00,2022/23,Superliga,Superliga,Brøndby IF,BIF,...,0.0,0.0,0.0,2022-07-24 15:13:18,12,1319753.98,2022-07-24 16:56:00,276.0,7,Sommer
2,623,2022-08-14,2022-08-14,2022-08-14 | Brøndby IF - OB,2022-08-14 18:00:00,2022/23,Superliga,Superliga,Brøndby IF,BIF,...,0.0,0.0,0.0,2022-08-14 17:40:50,11,1599700.90,2022-08-14 19:04:00,337.0,8,Sommer
3,624,2022-08-29,2022-08-29,2022-08-29 | Brøndby IF - FC Midtjylland,2022-08-29 19:00:00,2022/23,Superliga,Superliga,Brøndby IF,BIF,...,0.0,0.0,0.0,2022-08-29 18:44:52,12,1295286.41,2022-08-29 18:46:00,284.0,8,Sommer
4,653,2022-07-28,2022-07-28,2022-07-28 | Brøndby IF - Pogoń Szczecin,2022-07-28 20:00:00,2022/23,UEFA Europa Conference League,UEFA,Brøndby IF,BIF,...,0.0,0.0,0.0,2022-07-28 19:21:39,10,1455002.10,2022-07-28 20:56:00,278.0,7,Sommer
5,719,2022-08-04,2022-08-04,2022-08-04 | Brøndby IF - FC Basel,2022-08-04 20:30:00,2022/23,UEFA Europa Conference League,UEFA,Brøndby IF,BIF,...,0.0,0.0,0.0,2022-08-04 19:53:23,10,1366441.90,2022-08-04 21:22:00,301.0,8,Sommer
6,752,2022-09-11,2022-09-11,2022-09-11 | Brøndby IF - Randers FC,2022-09-11 16:00:00,2022/23,Superliga,Superliga,Brøndby IF,BIF,...,0.0,0.0,0.0,2022-09-11 15:42:52,14,1644799.16,2022-09-11 16:53:00,358.0,9,Efterår
7,818,2022-10-02,2022-10-02,2022-10-02 | Brøndby IF - Lyngby BK,2022-10-02 16:00:00,2022/23,Superliga,Superliga,Brøndby IF,BIF,...,0.0,0.0,0.0,2022-10-02 15:39:21,12,1447540.10,2022-10-02 16:51:00,351.0,10,Efterår
8,851,2022-10-30,2022-10-30,2022-10-30 | Brøndby IF - AaB,2022-10-30 18:00:00,2022/23,Superliga,Superliga,Brøndby IF,BIF,...,0.0,0.0,0.0,2022-10-30 18:23:55,11,1481784.04,2022-10-30 18:54:00,378.0,10,Efterår
9,884,2022-11-13,2022-11-13,2022-11-13 | Brøndby IF - Viborg FF,2022-11-13 16:00:00,2022/23,Superliga,Superliga,Brøndby IF,BIF,...,22.0,10.0,0.0,2022-11-13 16:33:11,13,1478809.44,2022-11-13 16:55:00,335.0,11,Efterår

In [131]:
print("tickets_sold" in tickets_summary.columns)
print(tickets_summary.columns.tolist())

True
['match_id', 'att_date', 'Kampdato', 'Kampnavn', 'Kampstart', 'Sæson', 'Turnering', 'Turneringstype', 'Hjemmehold', 'Hjemmeholdsforkortelse', 'Udehold', 'Udeholdsforkortelse', 'Kampdato_dt', 'tickets_sold', 'avg_scans', 'Billetabonnement', 'Partnerbillet', 'Solgt', 'Sæsonkort', 'VIP', 'Øvrige', '3F Nedre_', '3F Nedre_Blok 10', '3F Nedre_Blok 7', '3F Nedre_Blok 8', '3F Nedre_Blok 9', '3F Øvre_', '3F Øvre_Tårn 1', '3F Øvre_Tårn 2', '3F Øvre_Tårn 6', '3F Øvre_Tårn 7', '3F_Udefans', 'Carlsberg Svinget_', 'Carlsberg Svinget_Tårn 24/25', 'Carlsberg Svinget_Tårn 25', 'Carlsberg Svinget_Tårn 31/32', 'D-Tribune_Kørestol DFDS', 'D-Tribune_Udehold', 'DHL Tribunen (B)_Udebane (B)', 'Familie-tribunen_A1', 'Familie-tribunen_A2', 'Familie-tribunen_A3', 'Familie-tribunen_A4', 'Familie-tribunen_A5', 'GSV Mellem_', 'GSV Mellem_Kørestolsplateau', 'GSV Mellem_Tårn 17', 'GSV Mellem_Tårn 18', 'GSV Mellem_Tårn 22', 'GSV Mellem_Tårn 23', 'GSV Nedre_', 'GSV Nedre_Blok 1', 'GSV Nedre_Blok 2', 'GSV Nedre_Blok 3', 'GSV Nedre_Blok 4', 'GSV Nedre_Blok 5', 'GSV Nedre_Blok 6', 'GSV Øvre_', 'GSV Øvre_Tårn 17', 'GSV Øvre_Tårn 18', 'GSV Øvre_Tårn 19', 'GSV Øvre_Tårn 20', 'GSV Øvre_Tårn 21', 'GSV Øvre_Tårn 22', 'GSV Øvre_Tårn 23', 'HRH Svinget_', 'HRH Svinget_Tårn 15/16', 'Klub Europa Lounge_', 'Klub Europa Lounge_Tårn 3', 'Klub Europa Lounge_Tårn 4', 'Klub Europa Lounge_Tårn 5', 'Mascot/Udefans_Udebane Unum.', 'Michael Laudrup Lounge_', 'Michael Laudrup Lounge_Tårn 19', 'Michael Laudrup Lounge_Tårn 20', 'Michael Laudrup Lounge_Tårn 21', 'Południowa_121', 'Południowa_221', 'Południowa_222', 'SVINGET_Tårn 24/25', 'SVINGET_Tårn 25', 'Sparekassen Kronjylland Nedre_Blok 10', 'Sparekassen Kronjylland Nedre_Blok 7', 'Sparekassen Kronjylland Nedre_Blok 8', 'Sparekassen Kronjylland Nedre_Blok 9', 'Sparekassen Kronjylland Øvre_Tårn 1', 'Sparekassen Kronjylland Øvre_Tårn 2', 'Sparekassen Kronjylland Øvre_Tårn 6', 'Sparekassen Kronjylland Øvre_Tårn 7', 'Stavnskær Elektrik Nedre_', 'Stavnskær Elektrik Nedre_Blok 1', 'Stavnskær Elektrik Nedre_Blok 2', 'Stavnskær Elektrik Nedre_Blok 3', 'Stavnskær Elektrik Svinget_', 'Stavnskær Elektrik Svinget_Tårn 8/9', 'Stavnskær Elektrik Øvre_', 'Stavnskær Elektrik Øvre_Tårn 10', 'Stavnskær Elektrik Øvre_Tårn 11', 'Stavnskær Elektrik Øvre_Tårn 12', 'Stavnskær Elektrik Øvre_Tårn 13', 'Stavnskær Elektrik Øvre_Tårn 14', 'Super1Rent_B1 - Udebaneafsnit', 'Super1Rent_Udebaneafsnit', 'Sydsiden Nedre_', 'Sydsiden Nedre_Ståplads', 'Sydsiden Øvre_', 'Sydsiden Øvre_Tårn 25', 'Sydsiden Øvre_Tårn 26', 'Sydsiden Øvre_Tårn 27', 'Sydsiden Øvre_Tårn 28', 'Sydsiden Øvre_Tårn 29', 'Sydsiden Øvre_Tårn 30', 'Udebane_', 'Udebane_Nedre', 'Udebane_Tårn 14', 'Udebane_Udebane', 'Udebane_Øvre', 'Udefans_E1', 'Udefans_E2', 'Udehold / Away_U', 'Vilfort Lounge_', 'Vilfort Lounge_Blok 2', 'Vilfort Lounge_Blok 3', 'Vilfort Lounge_Blok 4', 'Vilfort Lounge_Blok 5', 'Vilfort Lounge_Blok 6', 'Vilfort Lounge_Hertha BSC Lounge', 'Vilfort Lounge_Legende Logen', 'Vilfort Lounge_Tårn 2', 'Vilfort Lounge_Tårn 3', 'Vilfort Lounge_Tårn 4', 'Vilfort Lounge_Tårn 5', 'Vilfort Lounge_Tårn 6', 'Zachodnia_225', 'peak_minute', 'peak_scans', 'total_revenue_DKK', 'fb_peak_time', 'fb_peak_orders', 'month', 'season_weather']

In [132]:
tickets_summary_view = tickets_summary[[
    "match_id", "Kampnavn", "Kampdato", "Kampstart",
    "Sæson", "Turnering", "Hjemmehold", "Udehold",
    "tickets_sold", "avg_scans", "peak_scans", "peak_minute",
    "total_revenue_DKK", "fb_peak_time", "fb_peak_orders"
]]

tickets_summary_view.head(10)

,match_id,Kampnavn,Kampdato,Kampstart,Sæson,Turnering,Hjemmehold,Udehold,tickets_sold,avg_scans,peak_scans,peak_minute,total_revenue_DKK,fb_peak_time,fb_peak_orders
0,621,2022-07-17 | Brøndby IF - AGF,2022-07-17,2022-07-17 18:00:00,2022/23,Superliga,Brøndby IF,AGF,11249,16908,14,2022-07-17 17:16:39,1485862.04,2022-07-17 18:55:00,254.0
1,622,2022-07-24 | Brøndby IF - FC Nordsjælland,2022-07-24,2022-07-24 16:00:00,2022/23,Superliga,Brøndby IF,FC Nordsjælland,11737,16845,12,2022-07-24 15:13:18,1319753.98,2022-07-24 16:56:00,276.0
2,623,2022-08-14 | Brøndby IF - OB,2022-08-14,2022-08-14 18:00:00,2022/23,Superliga,Brøndby IF,OB,11458,17822,11,2022-08-14 17:40:50,1599700.90,2022-08-14 19:04:00,337.0
3,624,2022-08-29 | Brøndby IF - FC Midtjylland,2022-08-29,2022-08-29 19:00:00,2022/23,Superliga,Brøndby IF,FC Midtjylland,10662,16544,12,2022-08-29 18:44:52,1295286.41,2022-08-29 18:46:00,284.0
4,653,2022-07-28 | Brøndby IF - Pogoń Szczecin,2022-07-28,2022-07-28 20:00:00,2022/23,UEFA Europa Conference League,Brøndby IF,Pogoń Szczecin,10451,15211,10,2022-07-28 19:21:39,1455002.10,2022-07-28 20:56:00,278.0
5,719,2022-08-04 | Brøndby IF - FC Basel,2022-08-04,2022-08-04 20:30:00,2022/23,UEFA Europa Conference League,Brøndby IF,FC Basel,15560,14907,10,2022-08-04 19:53:23,1366441.90,2022-08-04 21:22:00,301.0
6,752,2022-09-11 | Brøndby IF - Randers FC,2022-09-11,2022-09-11 16:00:00,2022/23,Superliga,Brøndby IF,Randers FC,15076,21661,14,2022-09-11 15:42:52,1644799.16,2022-09-11 16:53:00,358.0
7,818,2022-10-02 | Brøndby IF - Lyngby BK,2022-10-02,2022-10-02 16:00:00,2022/23,Superliga,Brøndby IF,Lyngby BK,13330,19023,12,2022-10-02 15:39:21,1447540.10,2022-10-02 16:51:00,351.0
8,851,2022-10-30 | Brøndby IF - AaB,2022-10-30,2022-10-30 18:00:00,2022/23,Superliga,Brøndby IF,AaB,12304,18616,11,2022-10-30 18:23:55,1481784.04,2022-10-30 18:54:00,378.0
9,884,2022-11-13 | Brøndby IF - Viborg FF,2022-11-13,2022-11-13 16:00:00,2022/23,Superliga,Brøndby IF,Viborg FF,13966,20984,13,2022-11-13 16:33:11,1478809.44,2022-11-13 16:55:00,335.0